# Generated by Django 5.2.10 on 2026-02-19 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='games/icons/')),
                ('url_name', models.CharField(help_text='Django URL name', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='game_name',
        ),
        migrations.AddField(
            model_name='gamescore',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='games.game'),
            preserve_default=False,
        ),
    ]
