# Generated by Django 5.2.10 on 2026-02-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_drawing'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Image name', max_length=100)),
                ('image', models.ImageField(upload_to='home_images/')),
                ('description', models.TextField(blank=True, help_text='Optional description for the image')),
            ],
        ),
    ]
