# Generated by Django 5.2.10 on 2026-02-19 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_homeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeimage',
            name='name',
        ),
    ]
